### ISSUE TITLE
allow for changing faktory environment in config

### ISSUE THREAD

**Issue by chrisvaughn** [AdWerx/charts#25]
Thanks for maintaining this helm chart.  Would it be possible to get a production/staging setting in the values.yaml to control the -e flag passed to the faktory server?  This will allow the use of enterprise features in a production-llke test environment. https://github.com/contribsys/faktory/wiki/Administration#in-staginghttps://github.com/contribsys/faktory/wiki/Administration#in-staging

https://github.com/AdWerx/charts/blob/b07443daaec98a163589f39de74b9620d8d2c3e7/faktory/templates/statefulset.yaml#L66-L67

I can attempt a PR if you're interested.

**Comment by jbielick** [comment]
Great idea. I've added this as a configurable value in `0.12.0`—the default is `production`.

**Comment by chrisvaughn** [comment]
Brilliant. Thanks!
