### ISSUE TITLE
chart ingress broken

### ISSUE THREAD

**Issue by jamesla** [AdWerx/charts#4]
hey i think the ingress in this chart is broken:

all you have to do is make a copy of values.yaml and flip ingress enabled to true and you will get the following:

```
helm install awx adwerx/awx --values values.yaml
Error: template: awx/templates/ingress.yaml:34:15: executing "awx/templates/ingress.yaml" at <.host>: can't evaluate field host in type interface {}
```

works fine when ingress.enabled is set to false

**Comment by jbielick** [comment]
Ah, yeah the default values don't have the correct schema. 

This has been fixed in `v2.0.3`.  https://github.com/AdWerx/charts/commit/7df9acf04b47d42fe2ccb21c8eb64a5ace3cb69d

Thanks for pointing this out!
