### ISSUE TITLE
Deprecated Ingress API version

### ISSUE THREAD

**Issue by aaronmanning613** [AdWerx/charts#42]
On GKE version 1.22 and later, the extensions/v1beta1 API version is no longer supported, it requires a migration to the networking.k8s.io/v1beta1 API version: https://kubernetes.io/blog/2019/07/18/api-deprecations-in-1-16/

Deploying faktory with any ingress resource fails with the error:
```
Error: UPGRADE FAILED: unable to recognize "": no matches for kind "Ingress" in version
"extensions/v1beta1"
```

**Comment by jbielick** [comment]
Thanks for the report. Could you put together a PR for this? I will merge and publish.

**Comment by aaronmanning613** [comment]
I am happy to put a PR together but it would change your k8s dependency quite a bit - the networking.k8s.io/v1 api version is supported on k8s >1.16, currently you support >1.9. Do you still want me to go through with the PR?

**Comment by aaronmanning613** [comment]
Hey @jbielick, I made those changes and my deployment seems to work fine - but I'm having issues trying to open a PR, I tried to go through the process described in the readme and run `bin/package faktory` but all the tests are failing. The tests also fail even when I clone the repo fresh and don't change anything.
